questions = [
    {"question": "Is Python an interpreted language?", "answer": "yes"},
    {"question": "Is Java platform-independent?", "answer": "yes"},
    {"question": "Is C a low-level language?", "answer": "no"},
    {"question": "Is indentation important in Python?", "answer": "yes"},
    {"question": "Is Java compiled directly to machine code?", "answer": "no"},
    {"question": "Is 'int' a data type in C?", "answer": "yes"},
    {"question": "Is Python statically typed?", "answer": "no"},
    {"question": "Is C++ object-oriented?", "answer": "yes"},
    {"question": "Is Kotlin used for Android development?", "answer": "yes"},
    {"question": "Is HTML a programming language?", "answer": "no"},
    {"question": "Is 'true' a boolean value?", "answer": "yes"},
    {"question": "Is 'false' a string?", "answer": "no"},
    {"question": "Is Java case-sensitive?", "answer": "yes"},
    {"question": "Is 'main' function necessary in C?", "answer": "yes"},
    {"question": "Can Python run on Linux?", "answer": "yes"},
    {"question": "Is Java a scripting language?", "answer": "no"},
    {"question": "Is Kotlin more concise than Java?", "answer": "yes"},
    {"question": "Is C++ an extension of C?", "answer": "yes"},
    {"question": "Is Python compiled before execution?", "answer": "no"},
    {"question": "Is Java code compiled to bytecode?", "answer": "yes"},
    {"question": "Is JavaScript the same as Java?", "answer": "no"},
    {"question": "Is 'int' a keyword in Java?", "answer": "yes"},
    {"question": "Does C support classes?", "answer": "no"},
    {"question": "Is C++ faster than Python?", "answer": "yes"},
    {"question": "Can Kotlin run on JVM?", "answer": "yes"},
    {"question": "Is '#' used for comments in Python?", "answer": "yes"},
    {"question": "Is Python code compiled into class files?", "answer": "no"},
    {"question": "Is JVM required to run Java?", "answer": "yes"},
    {"question": "Is Python dynamically typed?", "answer": "yes"},
    {"question": "Is 'null' a keyword in Java?", "answer": "yes"},
    {"question": "Is 'None' used in Python?", "answer": "yes"},
    {"question": "Is 'print' a function in Python 3?", "answer": "yes"},
    {"question": "Can Java run without JDK?", "answer": "no"},
    {"question": "Is 'elif' a keyword in Python?", "answer": "yes"},
    {"question": "Does C++ support multiple inheritance?", "answer": "yes"},
    {"question": "Is 'cout' used in C?", "answer": "no"},
    {"question": "Is Kotlin null-safe?", "answer": "yes"},
    {"question": "Is Python open-source?", "answer": "yes"},
    {"question": "Is Java compiled language?", "answer": "yes"},
    {"question": "Is C developed before C++?", "answer": "yes"},
    {"question": "Is JavaScript used for backend by default?", "answer": "no"},
    {"question": "Is Python good for beginners?", "answer": "yes"},
    {"question": "Is Kotlin better than Java in safety?", "answer": "yes"},
    {"question": "Is '&&' a logical operator in C?", "answer": "yes"},
    {"question": "Is 'def' a Python keyword?", "answer": "yes"},
    {"question": "Is Java used in web development?", "answer": "yes"},
    {"question": "Is Python a compiled language?", "answer": "no"},
    {"question": "Is 'import' used in Python?", "answer": "yes"},
    {"question": "Is Kotlin interoperable with Java?", "answer": "yes"},
    {"question": "Is 'elif' used in C?", "answer": "no"}
]

